services:
  hotmail-junk-removal:
    build: .
    container_name: hotmail_junk_removal
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - CLIENT_ID_FILE=/run/secrets/hotmail_client_id
      - DISCORD_URL_FILE=/run/secrets/discord_url
      - AUTH_DIRECTORY=/mnt/auth
    secrets:
      - hotmail_client_id
      - discord_url
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - auth:/mnt/auth
      - logs:/mnt/logs

secrets:
  hotmail_client_id:
    environment: HOTMAIL_CLIENT_ID
  discord_url:
    environment: DISCORD_URL_HOTMAIL

volumes:
  auth:
  logs:
