services:
  hotmail-junk-removal:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=America/New_Yorks
      - CLIENT_ID_FILE=/run/secrets/client_id.txt
      - DISCORD_URL_FILE=/run/secrets/discord_url.txt
    secrets:
      - hotmail_client_id
      - discord_url
    restart: unless-stopped

secrets:
  hotmail_client_id:
    name: hotmail_client_id
  discord_url:
    name: discord_url
